<?php $user = (!empty($this->authService)) ? $this->authService->getIdentity() : ''; ?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF3 Online Market')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Online Market
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
					<li><a href="<?= $this->url('home') ?>">Home</a></li>
					<li><a href="<?= $this->url('market/post') ?>">Post</a></li>
					</ul>
                    <!-- //*** NAVIGATION LAB: use the "navigation()" view helper instead of hard-coding menu items -->
                    <?php
                        if (isset($this->acl)) {
							//*** NAVIGATION LAB: get the role from the stored user identity
							//*** NAVIGATION LAB: set role and acl to navigation
                        }
                    ?>
                    <!-- //*** NAVIGATION LAB: set UL class to "nav navbar-nav" -->
                    <span style="float:right;color:white;">
						<!-- //*** AUTHENTICATION LAB: if auth service has an identity, display it, otherwise "guest" -->
                    </span>
                </div>
            </div>
        </nav>
        <div class="container">

            <div class="row">

                <div class="col-md-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Categories</h3>
                        </div>
                        <div class="panel-body">
							<!-- //*** NAVIGATION LAB: use Navigation to display list of categories -->
							<?php if (!empty($this->categories)) : ?>
							<ul class="no_bullets">
							<?php foreach ($this->categories as $item) : ?>
								<li><a href="<?= $this->url('market/view/category', ['category' => $item]) ?>"><?= ucfirst($item) ?></a></li>
							<?php endforeach; ?>
							</ul>
							<?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $this->content ?>
                        </div>
                        <hr>
                        <footer>
                            <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                        </footer>
                    </div>
                </div>

            </div>

        </div>

        <?= $this->inlineScript() ?>

    </body>
</html>
