<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas Online Market')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">&nbsp;Online Market
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav">
                    <li style="color:white;"><a href="<?= $this->url('home') ?>">- Home -</a></li>
                    <li style="color:white;"><a href="<?= $this->url('market/post') ?>">- Post -</a></li>
                    </ul>
                    <!-- //*** NAVIGATION LAB: use the "navigation()" view helper instead of hard-coding menu items -->
                    <?php
                        if (isset($this->acl)) {
                            //*** NAVIGATION LAB: get the role from the stored user identity
                            //*** NAVIGATION LAB: set role and acl to navigation
                        }
                    ?>
                    <!-- //*** NAVIGATION LAB: set UL class to "nav navbar-nav" -->
                    <span style="float:right;color:white;">
                        <!-- //*** AUTHENTICATION LAB: if auth service has an identity, display it, otherwise "guest" -->
                    </span>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Categories</h3>
                        </div>
                        <div class="panel-body">
                            <!-- //*** NAVIGATION LAB: use Navigation to display list of categories -->
                            <?php if (!empty($this->categories)) : ?>
                            <ul class="no_bullets">
                            <?php foreach ($this->categories as $item) : ?>
                                <li><a href="<?= $this->url('market/view/category', ['category' => $item]) ?>"><?= ucfirst($item) ?></a></li>
                            <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="col-md-10">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $this->content ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <hr>
                    <footer>
                        <p>&copy; 2005 - <?= date('Y') ?> <a href="https://www.zend.com/training">Zend by Perforce Training</a></p>
                    </footer>
                </div>
            </div>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
