<table style="font-size:16px" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td><?= date('d M, Y') . PHP_EOL; ?></td>
    </tr>
    <tr>
        <td><h1><?= $subject; ?></h1></td>
    </tr>
    <tr>
        <td>Dear
            <?= $this->registration->first_name . ' ' . $this->registration->last_name ?>,
        </td>
    </tr>
    <tr>
        <td>We are pleased to confirm the following people who will be attending <?= $this->event->name ?>:
            <ul>
                <?php foreach ($this->attendees as $attendee)
                    echo '<li>' . $attendee->name_on_ticket . '</li>'; ?>
            </ul>
        </td>
    </tr>
</table>