<!-- NOTE: these get echoed by "$this->headScript()" in the layout -->
<?= $this->headLink()->appendStylesheet('https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css'); ?>
<?= $this->headScript()->appendFile('https://code.jquery.com/jquery-3.5.1.js', ); ?>
<?= $this->headScript()->appendFile('https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js'); ?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <?= $this->translatePlural('Person', 'People', $this->val); ?>
                    <?= $this->translate('in'); ?>
                    <?= $this->translate('the Guestbook'); ?>
                </h3>
            </div>
            <div class="panel-body">
                <table width="100%" id="guestbook-table">
                <thead>
                <tr>
                    <th width="15%"><?= $this->translate('Name'); ?></th>
                    <th width="10%"><?= $this->translate('Avatar'); ?></th>
                    <th width="20%"><?= $this->translate('Email'); ?></th>
                    <th width="25%"><?= $this->translate('Date Signed'); ?></th>
                    <th width="30%"><?= $this->translate('Message'); ?></th>
                </tr>
                </thead>
                </table>
            </div>
        </div>
    </div>

</div>
<script>
$(document).ready(function() {
    $('#guestbook-table').DataTable( {
        "ajax": "/guestbook/guestbook/ajax"
    } );
} );
</script>
