<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Guestbook</span></h1>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Trigger Events</h3>
            </div>
            <div class="panel-body">
                <p>
                    <a href="/application/trigger-lazy">Trigger Lazy Listener</a> | 
                    <a href="/application/trigger-filter">Trigger Listener With Filter</a>
                </p>
            </div>
        </div>
    </div>
</div>
