<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
use Login\Entity\UserEntity;
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas Guestbook')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <!-- echos any "headScript()" commands issued in child views -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">&nbsp;Guestbook
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- set role and acl to navigation -->
                    <?php
                        $user = new UserEntity();
                        if ($this->authService) {
                            $user = $this->authService->getIdentity() ?? $user;
                        }
                        if (!empty($this->acl)) {
                            $this->navigation('default')->setAcl($this->acl);
                            $role = $user->getRole() ?? UserEntity::DEFAULT_USER;
                            $this->navigation('default')->setRole($role);
                        }
                    ?>
                    <?= $this->navigation('default')->menu()->setUlClass('nav navbar-nav'); ?>
                    <div style="color:white;vertical-align:top;margin-left:300px;">
                        <?= $user->getEmail() ?? UserEntity::DEFAULT_USER ?>
                        <?= ' [' . ($user->getLocale() ?? Locale::getDefault()) . ']'; ?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> <a href="https://www.zend.com/training">Zend by Perforce Training</a></p>
            </footer>
        </div>
    </body>
</html>
